### ISSUE TITLE
pip install moxie failing

### ISSUE THREAD

**Issue by jamesrustad** [quad/moxie#3]
Hi, I'm trying to get moxie going on my mac os x 10.15 install and running in to this problem when running 

`pip install moxie`

Any ideas?

```
pip install moxie
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting moxie
  Using cached moxie-8.12.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6q/r9mkx4cs7nv85h5qk_3b68740000gn/T/pip-install-R8huFV/moxie/setup.py'"'"'; __file__='"'"'/private/var/folders/6q/r9mkx4cs7nv85h5qk_3b68740000gn/T/pip-install-R8huFV/moxie/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6q/r9mkx4cs7nv85h5qk_3b68740000gn/T/pip-pip-egg-info-QxLqWF
         cwd: /private/var/folders/6q/r9mkx4cs7nv85h5qk_3b68740000gn/T/pip-install-R8huFV/moxie/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6q/r9mkx4cs7nv85h5qk_3b68740000gn/T/pip-install-R8huFV/moxie/setup.py", line 7, in <module>
        logging.info('GStreamer bindings should be installed: http://pygstdocs.berlios.de/')
    NameError: name 'logging' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by quad** [comment]
`pip install pygst`

See #2. But I need to merge the `elm` branch. 😓
